### ISSUE TITLE
[feature]导出页面文件（html，打开是目标页面）

### ISSUE THREAD

**Issue by cheng-kang** [LahK/AutoLayout-for-Web-Development#18]

**Comment by mrliaocn** [comment]
这部分我建议写一个`generate.js`，通过加载json来生成。即用户部署的时候也要引用这个`generate.js`。好处是我们在导入时正好也要写这个功能。

**Comment by mrliaocn** [comment]
如果可以的话，我就来做这部分了。

**Comment by cheng-kang** [comment]
@mrliaocn OK。你看一下 PAL 文件夹里面的 generate.js，是我之前写的根据 JSON 文件中的 objects 和 constraints 生成页面。
1. 之前的 generate.js 生成的页面并没有展现不同组件的样式，只是把对应位置生成了。
2. **数据格式**有变化，你看看新的导出文件，比对一下。

**Comment by cheng-kang** [comment]
开始修改的话，记得从 master branch 开一个新分支。

**Comment by cheng-kang** [comment]
@mrliaocn 标记完成之前记得先提交代码，然后和主分支合并。如果要把 'generate' 分支作为一个独立维护的分支的话，就把这个分支里面的其他代码都删掉；把代码全部移到根目录。
